# Generated by Django 4.2.1 on 2023-05-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='default', max_length=2150, unique=True),
            preserve_default=False,
        ),
    ]
