# Generated by Django 4.2.1 on 2023-05-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_brand_camera_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
