# Generated by Django 4.2.1 on 2023-05-23 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('gear_type', models.CharField(choices=[('LEN', 'Lens'), ('LIGHT', 'Lighting'), ('BATTERY', 'Battery'), ('MIC', 'Microphone'), ('TRIPOD', 'Tripod'), ('OTHER', 'Other')], max_length=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.brand')),
                ('camera', models.ManyToManyField(to='base.camera')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
