# Generated by Django 4.2.1 on 2023-05-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_gear_gear_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
