# Generated by Django 4.2.1 on 2023-05-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_gear_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='camera',
            field=models.ManyToManyField(related_name='gears', to='base.camera'),
        ),
    ]
